project:
  type: website
  output-dir: docs # when we render, put stuff in docs

website:
  title: "Melody Miu" # title of the website, top left
  navbar:
    left:
      - href: index.qmd # file
        text: Home # button
      - href: resume.qmd 
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



